app/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('news.urls')),
    path("__debug__/", include("debug_toolbar.urls")),
    path("", include("django.contrib.auth.urls")),
]

news/urls.py
from django.urls import path
from . import views

app_name = 'news'

urlpatterns = [
    path('', views.home, name="home"),
    path('news/', views.news, name="news"),
    path('news/<int:news_id>/', views.detail, name="detail"),
    path('news/<int:news_id>/comment/', views.comment, name="comment"),
    path('news/post/', views.news_post, name="post_news"),
    path('news/change/<int:news_id>/', views.NewsUpdate.as_view(), name="update"),
    path('signup/',views.signup,name="signup"),
    path("<int:news_id>/delete", views.delete_news, name="delete_news"),
    path("news/<int:news_id>/detail/<int:comment_id>/delete", views.delete_comment, name="delete_comment"),
    path("api/news/",views.news_api),
    path("api/news/<int:pk>/", views.NewsDetail.as_view()),

]

news/models.py
from django.db import models
from django.contrib.auth.models import User


class News(models.Model):
    title = models.CharField(max_length=150, blank=False)
    description = models.CharField(max_length=250, blank=True)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User,on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    def has_comments(self):
        return self.comment_set.exists()


class Comment(models.Model):
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    news = models.ForeignKey(News, on_delete=models.CASCADE)
    author = models.ForeignKey(User,on_delete=models.CASCADE)

news/forms.py
from django import forms
from .models import News
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class NewsForm(forms.ModelForm):
    title = forms.CharField(max_length=150, label="Title")
    description = forms.CharField(max_length=250,required=False)
    content = forms.CharField(widget=forms.Textarea, label="News Description")

    class Meta:
        model = News
        fields = ["title", "description", "content"]


class SignUpForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ["username", "email","password1", "password2"]

news/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, reverse, redirect
from django.core.paginator import Paginator
from .models import News, Comment
from .forms import NewsForm, SignUpForm
from django.views import View
from django.contrib import messages
from django.contrib.auth import login
from django.contrib.auth.models import Group
from django.contrib.auth.decorators import login_required, permission_required
from django.utils.decorators import method_decorator
from .serializers import NewsSerializer
from rest_framework import generics,status,serializers
from rest_framework.decorators import api_view
from rest_framework.response import Response

def home(request):
    return render(request, 'news/home.html')


def news(request):
    news_list = News.objects.order_by("-created_at")
    paginator = Paginator(news_list, 10)

    page_number = request.GET.get(request, 'page')
    page_obj = paginator.get_page(page_number)
    context = {'page_obj': page_obj}
    return render(request, 'news/news.html', context)


def detail(request, news_id):
    news_obj = get_object_or_404(News, pk=news_id)
    news_instance = News.objects.get(pk=news_id)
    comments = Comment.objects.order_by('-created_at').filter(news=news_instance)
    context = {"news_obj": news_obj, "comments": comments}
    return render(request, 'news/detail.html', context)


def comment(request, news_id):
    comment_post = request.POST["comment"]
    if comment_post != "":
        news_instance = News.objects.get(pk=news_id)
        comment_save_db = Comment(content=comment_post, news=news_instance, author=request.user)
        comment_save_db.save()

        return HttpResponseRedirect(reverse("news:detail", args=(news_id,)))
    return HttpResponseRedirect(reverse("news:detail", args=(news_id,)))


@login_required(login_url="/login")
@permission_required("news.add_news", login_url="/login")
def news_post(request):
    if request.method == "POST":
        form_post = NewsForm(request.POST)
        if form_post.is_valid():
            post = form_post.save(commit=False)
            post.author = request.user
            post.save()
            return HttpResponseRedirect(reverse("news:detail", args=(post.id,)))
    else:
        form_post = NewsForm(request.POST)
    return render(request, "news/post.html", {"form_post": form_post})


class NewsUpdate(View):
    @method_decorator(login_required(login_url="/login/"))
    def get(self, request, news_id):
        news_obj = get_object_or_404(News, pk=news_id)
        form_change = NewsForm(instance=news_obj)
        return render(request, "news/change.html", {"form_change": form_change, "news_data": news_obj})

    @method_decorator(login_required(login_url="/login/"))
    @method_decorator(permission_required("news.add_news", login_url="/login/"))
    def post(self, request, news_id):
        news_obj = get_object_or_404(News, pk=news_id)
        form_change = NewsForm(request.POST, instance=news_obj)
        if request.user == news_obj.author:
            if form_change.is_valid():
                update = form_change.save()
                messages.success(request, "You successfully updated the post")
                return HttpResponseRedirect(reverse("news:detail", args=(news_id,)))
        return render(request, "news/change.html", {"form_change": form_change, "news_data": news_obj})


def signup(request):
    if request.method == "POST":
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            group = Group.objects.get(name="default")
            group.user_set.add(user)
            login(request, user)
            return redirect('/')
    else:
        form = SignUpForm()

    return render(request, 'registration/signup.html', {"form": form})


@permission_required("news.delete_news", login_url="/login")
def delete_news(request, news_id):
    news_db = get_object_or_404(News, pk=news_id)
    if request.method == "POST":
        if news_db.author == request.user or request.user.has_perm("comment.delete_comment"):
            news_db.delete()

    return redirect(reverse("news:news"))


@permission_required("comment.delete_comment", login_url="/login")
def delete_comment(request, news_id, comment_id):
    news_db = get_object_or_404(News, pk=news_id)
    comment_db = get_object_or_404(Comment, pk=comment_id)
    if request.method == "POST":
        if request.user.username == comment_db.author.username or request.user.has_perm("comment.delete_comment"):
            comment_db.delete()

    return redirect(reverse("news:detail", args=(news_db.id,)))


@api_view(["POST", "GET"])
def news_api(request):
    if request.method == "POST":
        news_serializer = NewsSerializer(data=request.data)
        if news_serializer.is_valid():
            news_serializer.save()
            return Response(news_serializer.data,status=status.HTTP_201_CREATED)

        return Response(news_serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    if request.method == "GET":
        news_queryset = News.objects.all()
        serializer = NewsSerializer(news_queryset, many=True)
        return Response(serializer.data, status=status.HTTP_200_OK)


class NewsDetail(generics.RetrieveDestroyAPIView):
    queryset = News.objects.all()
    serializer_class = NewsSerializer

news/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'news/style.css' %}">
    <title>{% block title %}{% endblock %}</title>
    <style>
        .ps p{
            margin-left: 15px;
        }
    </style>
</head>
<body>
<header>
    <nav>
        <div class="sub-navbar">
            <div class="logo-container">
                <img src="{% static 'img/logo.jpg' %}" class="logo" alt="Spotify Logo"/>
                <a href="#" class="nav-link">News</a>
            </div>
            {% if user.is_authenticated %}
            <div class="ps">
                <p>Logged as @{{user.username}} || <a href="{% url 'logout' %}">Logout</a></p>
                {% else %}
                <p><a href="{% url 'login' %}">Login</a></p>
            </div>
            {% endif %}
        </div>
    </nav>
    <navbar>
        <div class="navbar">
            <div class="navbar-link"><a href="{% url 'news:home' %}">Home</a></div>
            <div class="navbar-link"><a href="{% url 'news:news' %}">News</a></div>
            {% if user.is_authenticated %}
            <div class="navbar-link"><a href="{% url 'news:post_news' %}">Post News</a></div>
            {% endif %}
        </div>
    </navbar>
</header>
<section>
    {% block content %}
    {% endblock %}
</section>
<footer>
    <p>&copy; 2023 News && Newspapper. All rights reserved. | Designed by YourName</p>
</footer>
<script>
    const slider = document.querySelector('.carousel');
    let isDown = false;
    let startX;
    let scrollLeft;

    window.addEventListener("scroll", function () {
        var navbar = document.querySelector('navbar')
        navbar.classList.toggle('sticky', window.scrollY > 0)
        navbar.classList.toggle('fade-in', window.scrollY > 0);

    })

    slider.addEventListener('mousedown', e => {
        isDown = true;
        slider.classList.add('active');
        startX = e.pageX - slider.offsetLeft;
        scrollLeft = slider.scrollLeft;
    });
    slider.addEventListener('mouseleave', _ => {
        isDown = false;
        slider.classList.remove('active');
    });
    slider.addEventListener('mouseup', _ => {
        isDown = false;
        slider.classList.remove('active');
    });
    slider.addEventListener('mousemove', e => {
        if (!isDown) return;
        e.preventDefault();
        const x = e.pageX - slider.offsetLeft;
        const SCROLL_SPEED = 1;
        const walk = (x - startX) * SCROLL_SPEED;
        slider.scrollLeft = scrollLeft - walk;
    });

</script>
</body>
</html>

news/templates/news/change.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Post News{% endblock %}

{% block content %}
<style>
    .post-container {
        max-width: 600px;
        margin: 0 auto;
        padding: 20px;
        box-shadow: 5px 10px 5px rgba(0, 0, 0, 0.22);
    }

    .post-container form {
        display: flex;
        flex-direction: column;
    }

    .post-container label {
        font-weight: bold;
        margin-bottom: 5px;
    }

    .post-container input {
        padding: 10px;
        margin-bottom: 10px;
        border: 1px solid #ccc;
        border-radius: 5px;
    }

    .post-container input[type="submit"] {
        background-color: #41ba7b;
        color: white;
        border: none;
        cursor: pointer;
        padding: 10px;
        border-radius: 5px;
        font-weight: bold;
        transition: background-color 0.3s ease;
    }

    .post-container input[type="submit"]:hover {
        background-color: #00b348;
    }

</style>
<h2>Update Post</h2>
<div class="post-container">
    <form action="{% url 'news:update' news_data.id %}" method="post">
        {% csrf_token %}
        <label for="id_title">Title:</label>
        <input type="text" name="title" maxlength="150" required="" id="id_title" value="{{news_data.title}}">
        <label for="id_description">Description:</label>
        <input type="text" name="description" maxlength="250" id="id_description" value="{{news_data.description}}">
        <label for="id_content">News Description:</label>
        <textarea name="content" cols="40" rows="10" required="" id="id_content">{{news_data.content}}</textarea>
        <input type="submit">
    </form>

</div>
{% endblock %}

news/templates/news/detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %}News {{news_obj.title}}{% endblock %}

{% block content %}
<style>
    .container-news {
        display: flex;
        flex-direction: column;
        align-items: center;
        margin-bottom: 20px;
    }

    .container-news img {
        max-width: 150px;
        margin-right: 20px;
        border: 1px solid #ccc;
    }

    .container-news div {
        flex: 1;
    }

    .container-news h2.Title {
        font-size: 24px;
        margin: 0;
        margin-bottom: 10px;
    }

    .container-news p {
        font-size: 16px;
        color: #444;
        margin: 0;
    }

    .container-comment {
        margin-top: 30px;
        padding-top: 20px;
        border-top: 1px solid #ccc;
    }

    .container-comment h2 {
        font-size: 20px;
        margin-bottom: 10px;
    }

    .container-comment form {
        margin-bottom: 15px;
    }

    .container-comment input {
        width: 100%;
        padding: 10px;
        border: 1px solid #ccc;
        border-radius: 5px;
    }

    .comment-box {
        border: 1px solid #ccc;
        padding: 10px;
        margin-top: 10px;
        background-color: #f7f7f7;
    }

    .comment-box p.user {
        font-weight: bold;
        margin: 0;
    }

    .comment-box {
        margin: 5px 0;
    }

    .form-container {
        display: flex;
        flex-direction: column;
        align-items: center;
        padding: 20px;
        background-color: #f2f2f2;
        border-radius: 10px;
        box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.2);
    }

    .comment-input {
        width: 100%;
        padding: 10px;
        margin-bottom: 10px;
        border: 1px solid #ccc;
        border-radius: 5px;
        font-size: 16px;
    }

    .submit-button:hover {
        background-color: #eae8e8;
    }


    .custom-button,.delete {
        display: inline-block;
        padding: 5px 10px;
        background-color: #c42525;
        color: white;
        text-decoration: none;
        border-radius: 5px;
        font-weight: bold;
        transition: background-color 0.3s ease-in-out;
    }

    .box a {
        margin-left: 15px;
    }
</style>
<div class="container-news">
    <div>
        <h2 class="Title" style="text-align: center">{{ news_obj.title }}</h2>
        <p>
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; {{news_obj.content}}
        </p>
        <p class="public-date" style="text-align: right;padding-top: 30px;color: black">Public date:
            {{news_obj.created_at }}</p>
    </div>

</div>
<div style="display: flex;justify-content: right;margin-top: 50px">
    {% if user == news_obj.author%}
    <div style="display: flex;" class="box">

        <a href="{% url 'news:update' news_obj.id %}" class="custom-button">Update News</a>
        <form action="{% url 'news:delete_news' news_obj.id %}" method="post">
            {% csrf_token %}
            <input type="submit" style="background-color: #00b348" value="Delete News" class="delete">
        </form>
    </div>
    {% endif %}
</div>

<div class="container-comment">
    <h2>Comments</h2>
    {% if user.is_authenticated %}
    <form action="{% url 'news:comment' news_obj.id %}" method="post">
        {% csrf_token %}
        <div class="form-container">
            <input class="comment-input" name="comment" placeholder="Comment">
            <input class="submit-button" type="submit" value="Send">
        </div>
    </form>
    {% else %}
    <p>That write comment, first authenticated </p>
    {% endif %}
    {% if comments %}
    {% for comm in comments %}
    <div class="comment-box">
        <div style="display: flex;justify-content: space-between">
            <p class="user">{{comm.author.username}}</p>
            <p style="color: black">{{comm.created_at}}</p>
        </div>
        <p class="content">
            {{comm.content}}
        </p>
        {% if user == comm.author %}
        <form action="{% url 'news:delete_comment' news_obj.id comm.id %}" method="post">
            {% csrf_token %}
            <button type="submit" style="background-color: #00b348" class="delete">Delete comment</button>
        </form>
        {% endif %}
    </div>
    {% endfor %}
    {% else %}
    <center>
        <h3>There are yet no comments</h3>
    </center>
    {% endif %}
</div>
{% endblock %}

news/templates/news/home.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Home{% endblock %}

{% block content %}
<div class="news-card">
    <img src="{% static 'img/newspaper.jpg' %}"/>
    <div class="news-text">
        <h2>News && Newspapper</h2>
        <p>Explore the most recent developments and stories making headlines worldwide. Get informed and engaged!</p>
    </div>
</div>
<div class="carousel">
    <div class="carousel-item">
        <img src="{% static 'img/image5.jpg' %}" alt="Image 3">
    </div>
    <div class="carousel-item">
        <img src="{% static 'img/war2.jpg' %}" alt="Image 2">
    </div>
    <div class="carousel-item">
        <img src="{% static 'img/image4.jpeg' %}" alt="Image 3">
    </div>
    <div class="carousel-item">
        <img src="{% static 'img/war2.jpg' %}" alt="Image 3">
    </div>
    <div class="carousel-item">
        <img src="{% static 'img/image3.webp' %}" alt="Image 3">
    </div>
</div>
<div style="padding-top: 20px;"></div>
<div class="about-us" id="About">
    <h1 style="font-size: 30px;">About Us</h1>
    <div style="display: flex;align-items: center;">
        <img src="{% static 'img/logo.jpg' %}" class="about-logo"/>
        <div style="flex: 1;">
            <p>Welcome to News - your trusted source for accurate, timely, and comprehensive news coverage from around
                the world. With a commitment to delivering unbiased, factual, and in-depth reporting, we strive to keep
                you informed and engaged with the latest events, trends, and developments that shape our rapidly
                changing world.
                <br>
                Our Mission

                At NewsWebsite.com, our mission is to provide a platform where information knows no boundaries. We
                believe that every individual has the right to access news that is transparent, reliable, and relevant.
                Our dedicated team of experienced journalists, reporters, and editors work tirelessly to bring you news
                stories that matter most, empowering you to make informed decisions and fostering a deeper understanding
                of global events.</p>
        </div>
    </div>
</div>
{% endblock %}

news/templates/news/news.html
{% extends 'base.html' %}
{% load static %}

{% block title %}News{% endblock %}

{% block content %}
<style>
    .title {
        color: black;
    }

    .title:hover {
        color: gray;
    }

    .custom-button,input[type="submit"]{
        display: inline-block;
        padding: 5px 10px;
        background-color: #c42525;
        color: white;
        text-decoration: none;
        border-radius: 5px;
        font-weight: bold;
        transition: background-color 0.3s ease-in-out;
    }

    .box a{
        margin-right: 15px;
    }
</style>
{% if page_obj %}
{% for news in page_obj %}
<div class="news-card">
    <img src="{% static 'img/newspaper.jpg' %}"/>
    <div class="news-text" style="flex-direction: column">
        <div style="margin-bottom: 35px">
            <a href="{% url 'news:detail' news.id %}" class="title"><h2>{{ news.title }}</h2></a>
            <p>{{ news.description }}</p>
        </div>
        {% if user == news.author%}
        <div style="display: flex;" class="box">
            <a href="{% url 'news:update' news.id %}" class="custom-button">Update News</a>
             <form action="{% url 'news:delete_news' news.id %}" method="post">
                {% csrf_token %}
                <input type="submit" style="background-color: #00b348" value="Delete News">
            </form>
        </div>
        {% endif %}
    </div>
    <div style="padding-top: 15px"></div>
</div>
{% endfor %}
{% else %}
<center><h1>There are not news</h1></center>
{% endif %}
<center>
    <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ page_obj.previous_page_number }}">previous</a>
            {% endif %}

            <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>

            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">next</a>
                <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>
</center>
{% endblock %}

news/templates/news/post.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Post News{% endblock %}

{% block content %}
<style>
    .post-container {
        max-width: 600px;
        margin: 0 auto;
        padding: 20px;
        box-shadow: 5px 10px 5px rgba(0, 0, 0, 0.22);
    }

    .post-container form {
        display: flex;
        flex-direction: column;
    }

    .post-container label {
        font-weight: bold;
        margin-bottom: 5px;
    }

    .post-container input {
        padding: 10px;
        margin-bottom: 10px;
        border: 1px solid #ccc;
        border-radius: 5px;
    }

    .post-container input[type="submit"] {
        background-color: #41ba7b;
        color: white;
        border: none;
        cursor: pointer;
        padding: 10px;
        border-radius: 5px;
        font-weight: bold;
        transition: background-color 0.3s ease;
    }

    .post-container input[type="submit"]:hover {
        background-color: #00b348;
    }

</style>
<div class="post-container">
    <form action="{% url 'news:post_news' %}" method="post">
        {% csrf_token %}
        <label>Title</label>
        <input name="title">
        <label>Short Description</label>
        <input name="description">
        <label>Content</label>
        <input name="content">
        <input type="submit">
    </form>

</div>
{% endblock %}